# Generated by Django 4.1 on 2022-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatchannel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
