# Generated by Django 4.1 on 2022-08-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channel', '0002_alter_chatchannel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatchannel',
            options={'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
    ]
