# Generated by Django 4.1.4 on 2022-12-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channel', '0004_chatchannel_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
