# Generated by Django 4.1.4 on 2022-12-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channel', '0007_chatchannel_admins_alter_chatchannel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannel',
            name='hashed_value',
            field=models.CharField(default='111111', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
