# Generated by Django 4.1.5 on 2023-01-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channel', '0010_alter_chatchannel_hashed_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatchannel',
            name='hashed_value',
            field=models.CharField(default='254817c1', max_length=10, unique=True),
        ),
    ]
