# Generated by Django 4.1 on 2022-08-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
    ]
