# Generated by Django 4.1 on 2022-08-07 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0004_chat_chatter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='content',
            new_name='message',
        ),
    ]
