# Generated by Django 4.1 on 2022-08-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat_channel', '0003_alter_chatchannel_options'),
        ('chat', '0005_rename_content_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat',
                                    to='chat_channel.chatchannel'),
        ),
    ]
