# Generated by Django 4.1.4 on 2022-12-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_file'),
        ('chat', '0009_alter_chat_chatter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file'),
        ),
    ]
