# Generated by Django 4.1.4 on 2023-01-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_chatbookmark_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
    ]
