# Generated by Django 4.1.5 on 2023-01-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-id'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
    ]
