# Generated by Django 4.1.4 on 2023-01-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_chatreaction_chatreaction_unique_reaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatReaction",
        ),
    ]
