# Generated by Django 4.1.5 on 2023-02-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_chat_options'),
        ('chat', '0015_delete_chatreaction'),
    ]

    operations = [
    ]
