# Generated by Django 4.1.4 on 2023-01-19 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0015_delete_chatreaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=10)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reaction",
                        to="chat.chat",
                    ),
                ),
                (
                    "reactors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reaction_reactors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Reaction",
                "verbose_name_plural": "Chat Reactions",
            },
        ),
        migrations.AddConstraint(
            model_name="chatreaction",
            constraint=models.UniqueConstraint(
                fields=("chat", "icon"), name="unique_reaction"
            ),
        ),
    ]
