# Generated by Django 4.1.4 on 2023-03-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_merge_20230201_1444"),
        ("chat_channel", "0012_alter_chatchannel_hashed_value"),
        ("chat_counter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counter",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat_channel.chatchannel",
            ),
        ),
        migrations.AlterField(
            model_name="counter",
            name="most_recent_chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chat",
            ),
        ),
    ]
