# Generated by Django 4.1.4 on 2023-03-04 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_channel", "0012_alter_chatchannel_hashed_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat_counter", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="counter",
            unique_together={("channel", "user")},
        ),
    ]
