# Generated by Django 4.1.3 on 2022-12-16 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='joined_workspaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
