# Generated by Django 4.1.4 on 2022-12-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='hashed_value',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
