# Generated by Django 4.1.4 on 2022-12-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_members'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='workspace',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to='workspace.workspace'),
            preserve_default=False,
        ),
    ]
